# Generated by Django 4.0.5 on 2022-06-08 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_Category', models.CharField(max_length=100)),
                ('Product_Short_Description', models.TextField(max_length=100)),
                ('Product_Full_Description', models.TextField(max_length=100)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Discount_price', models.CharField(max_length=100)),
                ('Product_Tag', models.CharField(max_length=500)),
                ('Product_Seo', models.CharField(max_length=500)),
                ('Product_Unit', models.CharField(default='', max_length=100)),
                ('Product_img', models.ImageField(max_length=200, upload_to='Products')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
