# Generated by Django 4.0.5 on 2022-06-08 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Discount_price', models.CharField(max_length=100)),
                ('Product_Unit', models.CharField(default='', max_length=100)),
                ('Product_img', models.CharField(default='', max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Discount_price', models.CharField(max_length=100)),
                ('Product_Unit', models.CharField(default='', max_length=100)),
                ('Product_img', models.CharField(default='', max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
