# Generated by Django 4.0.5 on 2022-06-08 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_addtocart_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('qmessage', models.CharField(default='', max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='addtocart',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
